name: Generate a build and deploy to static web hosting

on:
    push:
        branches:
            - master

jobs:
    build:
        runs-on: ubuntu-latest
        name: Build and Push

        steps:
            - name: git-checkout
              uses: actions/checkout@v3

            - name: Install all dependencies
              run: npm install

            - name: Build
              run: npx nuxi generate

            - name: Build for Static Hosting
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: static-build
                  FOLDER: dist
                  MESSAGE: "Build: ({sha}) {msg}"
                  GITHUB_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
